name: PlantUML Diagrams

on:
  push:
    branches:
      - sprint_3

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Склонировать репозиторий
        uses: actions/checkout@v2

      - name: Установить Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin" # Указание дистрибутива Java

      - name: Установить PlantUML
        run: sudo apt-get install plantuml -y

      - name: Генерация диаграмм
        run: |
          plantuml diagrams/context/*.puml
          plantuml diagrams/container/*.puml
          plantuml diagrams/component/*.puml
          plantuml diagrams/code/*.puml

      - name: Коммит диаграмм
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add diagrams/**/*.png
          git commit -m "Автоматическая генерация диаграмм"
          git push origin main
        if: success()
